name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rootvisar/angularinfo802
        tag_with_ref: true
        
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: AngularInfo802
        # Container registry password
        password: 4UaXcZqcAUfdkp=5LHBvCsM90AUMN6z8
        # Container registry server url
        login-server: angularinfo802.azurecr.io

    - name: App Service Web App Build Action
      uses: Azure/appservice-build@v2
     



