# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testvisar123

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rootvisar/angularinfo802
        tag_with_ref: true
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      uses: docker/login-action@v1.8.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: angular802
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        #logout: # optional, default is tr
      
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2.2.1
      with:
        push: true
        tags: angularinfo802:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testvisar123'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a18973fd44bd4f6aa8ffac75856ebf52 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5785a823884d458595fc7f627b1f2fa8 }}/angularinfo802:${{ github.sha }}'
