# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - visartest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_13c303a4eadb45f5a2a3534c67cf21e4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3de2951330114f18b3c141bf68ba87d8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2.2.1
      with:
        push: true
        tags:  angularinfo802:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'visartest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3cbe73dfc9aa4d54925a94f970d4cf25 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_13c303a4eadb45f5a2a3534c67cf21e4 }}/ angularinfo802:${{ github.sha }}'